- hosts: slave-1
  tasks:
    - name: Copy files to remote host
      copy:
        src: /var/lib/jenkins/workspace/ansible-copy-artifacts/target/
        dest: /tmp/copy-test/
        owner: kanneganti1101
        mode: 0755
